# Generated by Django 3.1 on 2020-10-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='User',
            new_name='user',
        ),
    ]
